# Generated by Django 5.1.4 on 2024-12-09 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicants', '0001_initial'),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=8)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applicants.applicant')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='schemes.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationBenefit',
            fields=[
                ('application_benefit_id', models.AutoField(primary_key=True, serialize=False)),
                ('awarded', models.BooleanField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_benefits', to='applications.application')),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes.benefit')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationEligibility',
            fields=[
                ('application_eligibility_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_met', models.BooleanField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_eligibility', to='applications.application')),
                ('eligibility_criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes.eligibilitycriteria')),
            ],
        ),
    ]
