# Generated by Django 5.1.4 on 2024-12-08 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityCriteria',
            fields=[
                ('eligibility_criterion_id', models.AutoField(primary_key=True, serialize=False)),
                ('criterion_type', models.CharField(max_length=50)),
                ('criterion_value', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_conditions', models.TextField(blank=True, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='schemes.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('benefit_id', models.AutoField(primary_key=True, serialize=False)),
                ('benefit_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='schemes.scheme')),
            ],
        ),
    ]
