# Generated by Django 5.1.4 on 2024-12-09 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=6, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=100, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('applicant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nric', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True)),
                ('date_of_birth', models.DateField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced')], max_length=8)),
                ('employment_status', models.CharField(choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed')], max_length=10)),
                ('retrenchment_date', models.DateField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=8, null=True)),
                ('current_education', models.CharField(blank=True, choices=[('pre-primary', 'pre-primary'), ('primary', 'primary'), ('secondary', 'secondary'), ('tertiary', 'tertiary'), ('not in education', 'not in education')], max_length=20, null=True)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completed_national_service', models.BooleanField(default=False)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicants.address')),
            ],
        ),
        migrations.CreateModel(
            name='HouseholdMember',
            fields=[
                ('householdmember_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('relationship_to_applicant', models.CharField(choices=[('Spouse', 'Spouse'), ('Parent', 'Parent'), ('Child', 'Child'), ('Grandparent', 'Grandparent'), ('Grandchild', 'Grandchild'), ('Sibling', 'Sibling'), ('Guardian', 'Guardian'), ('Ward', 'Ward')], max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_members', to='applicants.applicant')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_member_profile', to='applicants.people')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to='applicants.people'),
        ),
    ]
